//Count Type
const ADD_ONE = 'ADD_ONE';
const MINUS_ONE = 'MINUS_ONE';
const UPDATE_COUNT = "UPDATE_COUNT";
//Personne Type

const CREATE_PERSON = "CREATE_PERSON"


export { ADD_ONE, MINUS_ONE, UPDATE_COUNT, CREATE_PERSON }